repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          # - id: check-added-large-files
          - id: check-merge-conflict
          - id: check-symlinks

    - repo: https://github.com/psf/black
      rev: 23.9.1
      hooks:
          - id: black

    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            name: isort (python)
            args: ['--profile', 'black']

    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            additional_dependencies: ['flake8-bugbear']

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.3
      hooks:
          - id: prettier
            types: ['yaml', 'toml', 'json']
            args: ['--write', '--check']
